
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Aug  9 2020 12:39:00 +07 (Aug  9 2020 05:39:00 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(clk, flick, rst_n, lamps);
  input clk, flick, rst_n;
  output [15:0] lamps;
  wire clk, flick, rst_n;
  wire [15:0] lamps;
  wire [3:0] State;
  wire [4:0] current_led;
  wire Mode, UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_1, n_2,
       n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_170, n_183;
  DFFSRHQX1 \lamps_reg[7] (.RN (n_118), .SN (n_152), .CK (clk), .D
       (n_65), .Q (lamps[7]));
  DFFSRHQX1 \lamps_reg[1] (.RN (n_125), .SN (n_141), .CK (clk), .D
       (n_82), .Q (lamps[1]));
  DFFSRHQX1 \lamps_reg[6] (.RN (n_115), .SN (n_153), .CK (clk), .D
       (n_99), .Q (lamps[6]));
  DFFSRHQX1 \lamps_reg[15] (.RN (n_119), .SN (n_142), .CK (clk), .D
       (n_103), .Q (lamps[15]));
  DFFSRHQX1 \lamps_reg[9] (.RN (n_112), .SN (n_158), .CK (clk), .D
       (n_87), .Q (lamps[9]));
  DFFSRHQX1 \lamps_reg[11] (.RN (n_124), .SN (n_146), .CK (clk), .D
       (n_81), .Q (lamps[11]));
  DFFSRHQX1 \lamps_reg[12] (.RN (n_122), .SN (n_145), .CK (clk), .D
       (n_98), .Q (lamps[12]));
  DFFSRHQX1 \lamps_reg[13] (.RN (n_121), .SN (n_144), .CK (clk), .D
       (n_91), .Q (lamps[13]));
  DFFSRHQX1 \lamps_reg[0] (.RN (n_126), .SN (n_150), .CK (clk), .D
       (n_96), .Q (lamps[0]));
  DFFSRHQX1 \lamps_reg[14] (.RN (n_120), .SN (n_143), .CK (clk), .D
       (n_104), .Q (lamps[14]));
  DFFSRHQX1 \lamps_reg[2] (.RN (n_114), .SN (n_148), .CK (clk), .D
       (n_88), .Q (lamps[2]));
  DFFSRHQX1 \lamps_reg[3] (.RN (n_117), .SN (n_149), .CK (clk), .D
       (n_79), .Q (lamps[3]));
  DFFSRHQX1 \lamps_reg[4] (.RN (n_116), .SN (n_157), .CK (clk), .D
       (n_105), .Q (lamps[4]));
  DFFSRHQX1 \lamps_reg[10] (.RN (n_111), .SN (n_147), .CK (clk), .D
       (n_89), .Q (lamps[10]));
  DFFSRHQX1 \lamps_reg[8] (.RN (n_113), .SN (n_151), .CK (clk), .D
       (n_95), .Q (lamps[8]));
  SDFFSRX1 \State_reg[1] (.RN (n_128), .SN (n_155), .CK (clk), .D
       (n_100), .SI (State[1]), .SE (n_159), .Q (State[1]), .QN
       (UNCONNECTED));
  DFFSRHQX1 \lamps_reg[5] (.RN (n_135), .SN (n_140), .CK (clk), .D
       (n_85), .Q (lamps[5]));
  DFFSRHQX1 \State_reg[3] (.RN (n_132), .SN (n_136), .CK (clk), .D
       (n_60), .Q (State[3]));
  SDFFSRX1 \State_reg[2] (.RN (n_107), .SN (n_137), .CK (clk), .D
       (n_84), .SI (State[2]), .SE (n_159), .Q (State[2]), .QN
       (UNCONNECTED0));
  DFFSHQX1 Mode_reg(.SN (n_154), .CK (clk), .D (n_75), .Q (Mode));
  SDFFSRX1 \State_reg[0] (.RN (n_127), .SN (n_139), .CK (clk), .D
       (n_38), .SI (n_159), .SE (State[0]), .Q (State[0]), .QN
       (UNCONNECTED1));
  NAND2XL g5863__2398(.A (n_156), .B (lamps[9]), .Y (n_158));
  NAND2XL g5875__5107(.A (n_170), .B (lamps[4]), .Y (n_157));
  NAND2XL g5903__6260(.A (n_170), .B (n_32), .Y (n_155));
  NOR2XL g5862__4319(.A (n_133), .B (n_156), .Y (n_154));
  NAND2XL g5877__8428(.A (n_170), .B (lamps[6]), .Y (n_153));
  NAND2XL g5879__5526(.A (n_156), .B (lamps[7]), .Y (n_152));
  NAND2XL g5880__6783(.A (n_170), .B (lamps[8]), .Y (n_151));
  NAND2XL g5884__3680(.A (n_156), .B (n_6), .Y (n_150));
  NAND2XL g5874__1617(.A (n_170), .B (lamps[3]), .Y (n_149));
  NAND2XL g5872__2802(.A (n_156), .B (lamps[2]), .Y (n_148));
  NAND2XL g5864__1705(.A (n_170), .B (lamps[10]), .Y (n_147));
  NAND2XL g5865__5122(.A (n_156), .B (lamps[11]), .Y (n_146));
  NAND2XL g5866__8246(.A (n_170), .B (lamps[12]), .Y (n_145));
  NAND2XL g5867__7098(.A (n_156), .B (lamps[13]), .Y (n_144));
  NAND2XL g5868__6131(.A (n_170), .B (lamps[14]), .Y (n_143));
  NAND2XL g5869__1881(.A (n_170), .B (lamps[15]), .Y (n_142));
  NAND2XL g5871__5115(.A (n_156), .B (lamps[1]), .Y (n_141));
  OR2XL g5876__7482(.A (n_134), .B (n_138), .Y (n_140));
  OR2XL g5878__4733(.A (State[0]), .B (n_138), .Y (n_139));
  OR2XL g5870__6161(.A (n_106), .B (n_138), .Y (n_137));
  OR2XL g5873__9315(.A (n_131), .B (n_138), .Y (n_136));
  AOI21XL g5902__9945(.A0 (n_134), .A1 (n_130), .B0 (n_133), .Y
       (n_135));
  AOI21XL g5901__2883(.A0 (n_131), .A1 (n_130), .B0 (n_133), .Y
       (n_132));
  OAI2BB1X1 g5913__2346(.A0N (current_led[2]), .A1N (flick), .B0
       (n_108), .Y (n_129));
  INVX1 g5904(.A (n_138), .Y (n_156));
  AOI21XL g5899__1666(.A0 (n_52), .A1 (n_130), .B0 (n_133), .Y (n_128));
  AOI21XL g5883__7410(.A0 (State[0]), .A1 (n_130), .B0 (n_133), .Y
       (n_127));
  AOI21XL g5900__6417(.A0 (n_5), .A1 (n_130), .B0 (n_133), .Y (n_126));
  DFFRX1 \current_led_reg[3] (.RN (rst_n), .CK (clk), .D (n_110), .Q
       (current_led[3]), .QN (n_28));
  OA21X1 g5890__5477(.A0 (lamps[1]), .A1 (n_123), .B0 (rst_n), .Y
       (n_125));
  OA21X1 g5885__2398(.A0 (lamps[11]), .A1 (n_123), .B0 (n_183), .Y
       (n_124));
  OA21X1 g5886__5107(.A0 (lamps[12]), .A1 (n_123), .B0 (rst_n), .Y
       (n_122));
  OA21X1 g5887__6260(.A0 (lamps[13]), .A1 (n_123), .B0 (n_183), .Y
       (n_121));
  OA21X1 g5888__4319(.A0 (lamps[14]), .A1 (n_123), .B0 (rst_n), .Y
       (n_120));
  OA21X1 g5889__8428(.A0 (lamps[15]), .A1 (n_123), .B0 (n_183), .Y
       (n_119));
  NAND2XL g5906__5526(.A (n_183), .B (n_130), .Y (n_138));
  OA21X1 g5895__6783(.A0 (lamps[7]), .A1 (n_123), .B0 (n_183), .Y
       (n_118));
  OA21X1 g5892__3680(.A0 (lamps[3]), .A1 (n_123), .B0 (rst_n), .Y
       (n_117));
  OA21X1 g5893__1617(.A0 (lamps[4]), .A1 (n_123), .B0 (n_183), .Y
       (n_116));
  OA21X1 g5894__2802(.A0 (lamps[6]), .A1 (n_123), .B0 (rst_n), .Y
       (n_115));
  OA21X1 g5891__1705(.A0 (lamps[2]), .A1 (n_123), .B0 (n_183), .Y
       (n_114));
  OA21X1 g5896__5122(.A0 (lamps[8]), .A1 (n_123), .B0 (rst_n), .Y
       (n_113));
  OA21X1 g5897__8246(.A0 (lamps[9]), .A1 (n_123), .B0 (n_183), .Y
       (n_112));
  OA21X1 g5898__7098(.A0 (lamps[10]), .A1 (n_123), .B0 (rst_n), .Y
       (n_111));
  OAI211X1 g5907__6131(.A0 (n_28), .A1 (n_20), .B0 (n_72), .C0 (n_92),
       .Y (n_110));
  XNOR2X1 g5908__1881(.A (current_led[4]), .B (n_94), .Y (n_109));
  AOI222X1 g5936__5115(.A0 (n_76), .A1 (n_33), .B0 (n_77), .B1 (n_93),
       .C0 (n_30), .C1 (n_10), .Y (n_108));
  AOI21XL g5905__7482(.A0 (n_106), .A1 (n_101), .B0 (n_133), .Y
       (n_107));
  INVXL g5910(.A (n_123), .Y (n_130));
  OAI21X1 g5914__4733(.A0 (n_56), .A1 (n_97), .B0 (n_71), .Y (n_105));
  OAI21X1 g5912__6161(.A0 (n_45), .A1 (n_102), .B0 (n_67), .Y (n_104));
  OAI21X1 g5917__9315(.A0 (n_90), .A1 (n_102), .B0 (n_73), .Y (n_103));
  NAND2X2 g5911__9945(.A (n_7), .B (n_101), .Y (n_123));
  MXI2XL g5921__2883(.A (n_83), .B (n_53), .S0 (State[3]), .Y (n_100));
  OAI21X1 g5920__2346(.A0 (n_49), .A1 (n_102), .B0 (n_66), .Y (n_99));
  OAI21X1 g5919__1666(.A0 (n_58), .A1 (n_97), .B0 (n_69), .Y (n_98));
  OAI21X1 g5928__7410(.A0 (n_25), .A1 (n_97), .B0 (n_74), .Y (n_96));
  OAI21X1 g5933__6417(.A0 (n_39), .A1 (n_97), .B0 (n_64), .Y (n_95));
  OAI211X1 g5916__5477(.A0 (current_led[3]), .A1 (n_36), .B0 (n_35),
       .C0 (n_93), .Y (n_94));
  AOI31X1 g5918__2398(.A0 (n_34), .A1 (n_70), .A2 (n_93), .B0 (n_41),
       .Y (n_92));
  OAI21X1 g5922__5107(.A0 (n_90), .A1 (n_86), .B0 (n_46), .Y (n_91));
  OAI21X1 g5931__6260(.A0 (n_47), .A1 (n_102), .B0 (n_63), .Y (n_89));
  OAI21X1 g5929__4319(.A0 (n_43), .A1 (n_102), .B0 (n_54), .Y (n_88));
  OAI21X1 g5934__8428(.A0 (n_80), .A1 (n_86), .B0 (n_48), .Y (n_87));
  OAI21X1 g5935__5526(.A0 (n_42), .A1 (n_86), .B0 (n_50), .Y (n_85));
  MXI2XL g5937__6783(.A (n_23), .B (n_83), .S0 (State[3]), .Y (n_84));
  OAI21X1 g5938__3680(.A0 (n_78), .A1 (n_86), .B0 (n_44), .Y (n_82));
  OAI21X1 g5945__1617(.A0 (n_80), .A1 (n_102), .B0 (n_59), .Y (n_81));
  OAI21X1 g5950__2802(.A0 (n_78), .A1 (n_102), .B0 (n_57), .Y (n_79));
  OAI31X1 g5966__1705(.A0 (current_led[0]), .A1 (current_led[2]), .A2
       (n_76), .B0 (n_37), .Y (n_77));
  XNOR2X1 g5953__5122(.A (Mode), .B (n_159), .Y (n_75));
  OAI21X1 g5951__8246(.A0 (n_78), .A1 (n_68), .B0 (lamps[0]), .Y
       (n_74));
  OAI21X1 g5923__7098(.A0 (n_1), .A1 (n_72), .B0 (lamps[15]), .Y
       (n_73));
  NOR4X1 g5915__6131(.A (current_led[4]), .B (current_led[3]), .C
       (n_31), .D (n_93), .Y (n_101));
  OAI2BB1X1 g5924__1881(.A0N (n_70), .A1N (n_26), .B0 (lamps[4]), .Y
       (n_71));
  OAI21X1 g5925__5115(.A0 (n_90), .A1 (n_68), .B0 (lamps[12]), .Y
       (n_69));
  OAI21X1 g5926__7482(.A0 (n_90), .A1 (n_62), .B0 (lamps[14]), .Y
       (n_67));
  OAI2BB1X1 g5927__4733(.A0N (n_70), .A1N (n_27), .B0 (lamps[6]), .Y
       (n_66));
  OAI2BB1X1 g5932__6161(.A0N (n_70), .A1N (n_17), .B0 (n_40), .Y
       (n_65));
  OAI21X1 g5947__9315(.A0 (n_80), .A1 (n_68), .B0 (lamps[8]), .Y
       (n_64));
  OAI21X1 g5952__9945(.A0 (n_80), .A1 (n_62), .B0 (lamps[10]), .Y
       (n_63));
  XNOR2X1 g5954__2883(.A (current_led[1]), .B (n_24), .Y (n_61));
  AND2X1 g5957__2346(.A (State[3]), .B (n_159), .Y (n_60));
  OAI21X1 g5962__1666(.A0 (n_58), .A1 (n_55), .B0 (lamps[11]), .Y
       (n_59));
  OAI21X1 g5963__7410(.A0 (n_56), .A1 (n_55), .B0 (lamps[3]), .Y
       (n_57));
  XNOR2X1 g5939__6417(.A (State[3]), .B (n_51), .Y (n_131));
  OAI21X1 g5949__5477(.A0 (n_78), .A1 (n_62), .B0 (lamps[2]), .Y
       (n_54));
  AOI21X1 g5941__2398(.A0 (State[2]), .A1 (n_52), .B0 (n_51), .Y
       (n_53));
  OAI21X1 g5942__5107(.A0 (n_49), .A1 (n_62), .B0 (lamps[5]), .Y
       (n_50));
  OAI21X1 g5943__6260(.A0 (n_47), .A1 (n_62), .B0 (lamps[9]), .Y
       (n_48));
  OAI21X1 g5940__4319(.A0 (n_45), .A1 (n_62), .B0 (lamps[13]), .Y
       (n_46));
  OAI21X1 g5948__8428(.A0 (n_43), .A1 (n_62), .B0 (lamps[1]), .Y
       (n_44));
  NOR2XL g5946__5526(.A (lamps[5]), .B (n_70), .Y (n_134));
  INVX1 g5955(.A (n_70), .Y (n_42));
  OAI2BB1X1 g5964__6783(.A0N (n_29), .A1N (n_13), .B0 (n_45), .Y
       (n_41));
  OAI21X1 g5965__3680(.A0 (n_39), .A1 (n_55), .B0 (lamps[7]), .Y
       (n_40));
  INVX1 g5977(.A (n_159), .Y (n_38));
  INVX1 g5976(.A (n_36), .Y (n_37));
  OAI2BB1X1 g5944__1617(.A0N (n_34), .A1N (n_33), .B0 (current_led[3]),
       .Y (n_35));
  MX2X1 g5967__2802(.A (n_32), .B (n_22), .S0 (State[2]), .Y (n_83));
  OR2X1 g5958__1705(.A (n_30), .B (n_16), .Y (n_31));
  OR3X1 g5959__5122(.A (n_29), .B (n_11), .C (flick), .Y (n_72));
  NAND2X1 g5960__8246(.A (current_led[3]), .B (n_33), .Y (n_90));
  AND2X1 g5961__7098(.A (n_28), .B (n_33), .Y (n_70));
  INVX1 g5969(.A (n_62), .Y (n_27));
  NOR2X1 g5981__6131(.A (current_led[2]), .B (n_29), .Y (n_36));
  INVX1 g5968(.A (n_26), .Y (n_68));
  OR2X1 g5982__1881(.A (n_25), .B (n_12), .Y (n_159));
  ADDHX1 g5956__5115(.A (n_21), .B (n_2), .CO (n_51), .S (n_106));
  NAND2X1 g5971__7482(.A (n_9), .B (n_93), .Y (n_24));
  NOR2X1 g5972__4733(.A (current_led[1]), .B (n_55), .Y (n_26));
  OR2XL g5973__6161(.A (current_led[1]), .B (n_97), .Y (n_86));
  DFFRX1 \current_led_reg[0] (.RN (rst_n), .CK (clk), .D (n_8), .Q
       (n_14), .QN (current_led[0]));
  OR2X2 g5974__9315(.A (n_3), .B (n_55), .Y (n_62));
  MX2X1 g5979__9945(.A (n_15), .B (n_22), .S0 (n_21), .Y (n_23));
  AOI21X1 g5978__2883(.A0 (current_led[2]), .A1 (n_76), .B0 (flick), .Y
       (n_20));
  OR3X1 g5997__2346(.A (n_19), .B (n_18), .C (n_28), .Y (n_58));
  OR3X1 g5998__1666(.A (n_19), .B (current_led[3]), .C (n_18), .Y
       (n_56));
  INVX1 g5983(.A (n_32), .Y (n_52));
  INVX1 g5992(.A (n_17), .Y (n_102));
  ADDHX1 g5970__7410(.A (n_14), .B (current_led[2]), .CO (n_33), .S
       (n_16));
  OR2X1 g5986__6417(.A (Mode), .B (n_18), .Y (n_29));
  NAND2X1 g5990__5477(.A (n_22), .B (n_15), .Y (n_32));
  NAND2X1 g5989__2398(.A (n_14), .B (n_13), .Y (n_80));
  NAND2BX1 g5996__5107(.AN (n_18), .B (n_13), .Y (n_39));
  NAND2X1 g5995__6260(.A (current_led[0]), .B (n_13), .Y (n_47));
  NOR2X1 g6001__4319(.A (n_76), .B (n_12), .Y (n_17));
  OR2X1 g5999__8428(.A (n_18), .B (n_11), .Y (n_25));
  OR2X1 g5985__5526(.A (n_14), .B (n_11), .Y (n_43));
  NAND2X1 g5984__6783(.A (n_28), .B (n_10), .Y (n_49));
  INVX1 g6009(.A (n_76), .Y (n_34));
  NAND2X1 g5987__3680(.A (current_led[3]), .B (n_10), .Y (n_45));
  OR2X1 g5988__1617(.A (current_led[0]), .B (n_11), .Y (n_78));
  XNOR2X1 g5993__2802(.A (Mode), .B (n_14), .Y (n_9));
  XNOR2X1 g5994__1705(.A (n_14), .B (flick), .Y (n_8));
  OR4X1 g5980__5122(.A (State[1]), .B (State[3]), .C (n_0), .D (n_21),
       .Y (n_7));
  INVXL g6008(.A (n_5), .Y (n_6));
  OR2XL g5991__8246(.A (Mode), .B (n_12), .Y (n_55));
  OR2X1 g6000__7098(.A (n_4), .B (n_12), .Y (n_97));
  NAND2X1 g6010__6131(.A (n_4), .B (n_3), .Y (n_30));
  INVX1 g6002(.A (n_2), .Y (n_15));
  AND2X1 g6005__1881(.A (n_19), .B (current_led[3]), .Y (n_13));
  NOR2XL g6011__5115(.A (n_19), .B (lamps[0]), .Y (n_5));
  OR2X1 g6007__7482(.A (n_14), .B (current_led[1]), .Y (n_18));
  OR2X1 g6014__4733(.A (n_4), .B (n_3), .Y (n_76));
  AND2X1 g6004__6161(.A (current_led[0]), .B (current_led[2]), .Y
       (n_10));
  OR2X2 g6013__9315(.A (current_led[4]), .B (flick), .Y (n_12));
  NOR2X1 g6006__9945(.A (State[0]), .B (State[1]), .Y (n_2));
  NAND2X1 g6003__2883(.A (State[1]), .B (State[0]), .Y (n_22));
  OR2X1 g6012__2346(.A (current_led[2]), .B (current_led[3]), .Y
       (n_11));
  INVX1 g6018(.A (State[2]), .Y (n_21));
  INVXL g6016(.A (State[0]), .Y (n_0));
  INVX1 g6021(.A (Mode), .Y (n_4));
  INVX1 g6022(.A (flick), .Y (n_93));
  INVXL g6024(.A (rst_n), .Y (n_133));
  BUFX2 drc_buf_sp6057(.A (n_156), .Y (n_170));
  BUFX2 drc_buf_sp6069(.A (rst_n), .Y (n_183));
  DFFRX1 \current_led_reg[4] (.RN (rst_n), .CK (clk), .D (n_109), .Q
       (current_led[4]), .QN (n_1));
  DFFRX1 \current_led_reg[1] (.RN (rst_n), .CK (clk), .D (n_61), .Q
       (current_led[1]), .QN (n_3));
  DFFRX1 \current_led_reg[2] (.RN (rst_n), .CK (clk), .D (n_129), .Q
       (current_led[2]), .QN (n_19));
endmodule

